name: StyleOn_Workflow

on:
  push:
    branches:
    - Development

jobs:
  build:

    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=12.4,name=iPhone 11']

    steps:
    - uses: actions/checkout@master
    - name: Build
      run: swift build -v

  test:
      name: Test
      runs-on: macOS-latest
      strategy:
          matrix:
            destination: ['platform=iOS Simulator,OS=12.4,name=iPhone 11 Pro Max']

      # steps:
      #   - name: Checkout
      #     uses: actions/checkout@Development
      #   - name: Run tests
      #     run: swift test -v

      before_script: cd Style-On-cosmetic-app

      script:
        - xcodebuild clean test -project StyleOn.xcodeproj -scheme StyleOn -destination "$DESTINATION" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO